[build]
  publish = "public"
  command = "echo 'No build required'"

[[redirects]]
  from = "/"
  to = "/medsim-privacy.html"
  status = 200

[[redirects]]
  from = "/medsim-privacy"
  to = "/medsim-privacy.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
