name: Deploy MedSim Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write # Required for Workload Identity Federation

env:
  PROJECT_ID: promptedvisionsai
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: medsim-bot@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: medsim-bot
          region: ${{ env.REGION }}
          source: .
          env_vars: |
            NODE_ENV=production
            GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }}
            PROJECT_ID=${{ env.PROJECT_ID }}
            VERTEX_LOCATION=${{ env.REGION }}
            REGION=${{ env.REGION }}
